#
# Install javascripts
#

PREFIX = ~/public_html
SituationalAwarenessDir = $(PREFIX)/SituationalAwareness

LEAFLET = leaflet

all:

install:
	install --compare --backup --directory --target-directory=$(SituationalAwarenessDir) -D $(LEAFLET)
